### ISSUE TITLE
stopforumspam plugin has no api key input

### ISSUE THREAD

**Issue by Marcin-Kozyra** [pupi1985/q2a-pupi-srs#1]
![Screenshot from 2022-10-04 19-29-45](https://user-images.githubusercontent.com/1209361/193954511-bc7d44c3-505e-4660-ae6e-afb14eedf9a5.png)

**Comment by pupi1985** [comment]
The StopForumSpam API key is only used for spam user (reporting). The plugin is only used for checking status of the users, so the plugin key is irrelevant.
